# Generated by Django 2.1 on 2020-11-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainitem_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='result',
            field=models.IntegerField(default=50),
        ),
    ]
