# Generated by Django 2.1 on 2020-11-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201118_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='content',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mainitem',
            name='result',
            field=models.IntegerField(max_length=3),
        ),
    ]
