# Generated by Django 2.1 on 2020-12-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201119_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='negative_tweets',
            field=models.CharField(default='negative_tweets', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainitem',
            name='positive_tweets',
            field=models.CharField(default='positive_tweets', max_length=300),
            preserve_default=False,
        ),
    ]
